### ISSUE TITLE
Question : minimum requirements for singularity workbench session image? 

### ISSUE THREAD

**Issue by yukio-takeuchi** [sol-eng/singularity-rstudio#11]
I set up the spank plugin onto slurm at a server in my office. It also runs workbench 2023.06.
I am very impressed running a r-session by a singularity container. 

Please allow me to make a primitive question.
What is the minimum requirement for a singularity container to this pupose with slurm job launcher with this spank plugin?
I initially successfully run the r-session-complete.sif.
Then I was also able to use a sif built from the rocker/r-ver docker image with workbench installed.
However I failed to use an another sif built from rocker/r-ver with workbench session component which is provided by Posit for nodes to be used with slurm job launcher.

I suspect, I may at least need

- at least one version of R
- workbench   

Of course, I realized r-session-complete.sif built from r-session-complete.sdef also installs e.g. slurm.
However to me it is useful to know minimum requirements, too.

Thanks in advance

**Comment by yukio-takeuchi** [comment]
I am very sorry but I confirmed that r-ver + session component singularity sif also worked.
Previous failure may be due to the problem caused by recent kernel update of Ubuntu on loop device creation
```
https://github.com/sylabs/singularity/issues/1499
```
However if any infomation for minimum requirements for singularity image to be used is welcome

**Comment by michaelmayer2** [comment]
The minimum requirements for a singularity container to 

- run the RStudio IDE: Session Components + at least one version of R 
- run Jupyter/JupyterLab: Session Components + at least one version of Python (you may want to use https://github.com/rstudio/rstudio-docker-products/blob/main/r-session-complete/Dockerfile.ubuntu2204#L41-L53 to help installing the appropriate packages) 
- run VSCode: Session Components (but R and Python installation + extensions will be helpful if you want to code with R or Python)  

The installation of SLURM within the Singularity Container is only needed if you intend to submit additional SLURM jobs from within the container. Please make sure you use the same SLURM version in the container and on the actual HPC cluster.

**Comment by michaelmayer2** [comment]
Hope the information given was helpful - closing for now.
